apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'geth'
        static_configs:
          - targets: ['geth:8545']
      - job_name: 'node'
        static_configs:
          - targets: ['localhost:9100']
