apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
data:
  jwt.hex: MjhiMDk1ZDFmNWM1YzMwMjhmODVlOTU4MjgzYTY1ZjU5MTA2ZWVhZjAwMjIyYzZkNDc0YzI3YjQ4YWY4ZjcxZg== # Run `base64 jwt.hex` to encode
