apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-tuner
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: sysctl-tuner
  template:
    metadata:
      labels:
        name: sysctl-tuner
    spec:
      hostPID: true
      containers:
      - name: sysctl
        image: busybox
        command:
        - sh
        - -c
        - |
          sysctl -w net.core.somaxconn=1024
          sysctl -w net.core.netdev_max_backlog=5000
          sysctl -w net.ipv4.tcp_max_syn_backlog=4096
          sysctl -w net.ipv4.tcp_tw_reuse=1
          sysctl -w net.ipv4.tcp_syncookies=1
          sleep 3600
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /proc/sys
          name: sys
      volumes:
      - name: sys
        hostPath:
          path: /proc/sys
